### ISSUE TITLE
Screensaver is ended prematurely

### ISSUE THREAD

**Issue by farnoy** [Maassoft/ColorControl#104]
<details>
<summary>Here are the logs</summary>

```
2022-05-20 20:58:10.4300|DEBUG|ColorControl.LgService|Screensaver check: test connection result: True
2022-05-20 20:58:10.4300|DEBUG|ColorControl.LgService|Screensaver check: powering off tv LG salon TV because of screensaver
2022-05-20 20:58:10.5207|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2022-05-20 20:58:10.5207|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-05-20 20:58:10.5353|DEBUG|ColorControl.LgDevice|[LG salon TV] PictureSettingsChanged: {"contrast":85,"backlight":"20","brightness":50,"color":50}
2022-05-20 20:58:10.5353|DEBUG|ColorControl.LgDevice|[LG salon TV] ForegroundAppChanged: {"appId":"com.webos.app.hdmi2","subscribed":true,"returnValue":true,"windowId":"","processId":""}
2022-05-20 20:58:10.5672|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Power Off","onOff":"off","reason":"remoteKey"}
2022-05-20 20:58:10.5672|DEBUG|ColorControl.LgDevice|PoweredOffBy: App, PoweredOffViaApp: True
2022-05-20 20:58:10.5878|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Active Standby","onOff":"off","reason":"remoteKey"}
2022-05-20 20:58:10.5878|DEBUG|ColorControl.LgDevice|PoweredOffBy: App, PoweredOffViaApp: True
2022-05-20 20:58:10.5878|DEBUG|ColorControl.LgService|Screensaver check: powered off tv LG salon TV
2022-05-20 20:58:10.6325|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Suspend","onOff":"off","reason":"remoteKey"}
2022-05-20 20:58:10.6325|DEBUG|ColorControl.LgDevice|PoweredOffBy: App, PoweredOffViaApp: True
2022-05-20 20:58:10.6612|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Prepare Suspend","onOff":"off","reason":"remoteKey"}
2022-05-20 20:58:10.6612|DEBUG|ColorControl.LgDevice|PoweredOffBy: App, PoweredOffViaApp: True
2022-05-20 20:58:10.8719|DEBUG|ColorControl.LgDevice|[LG salon TV] ForegroundAppChanged: {"subscribed":true,"appId":"","returnValue":true,"windowId":"","processId":""}
2022-05-20 20:58:11.5827|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Suspend"}
2022-05-20 20:58:11.5827|DEBUG|ColorControl.LgDevice|PoweredOffBy: App, PoweredOffViaApp: True
2022-05-20 20:58:51.0630|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: status: Timeout, exception: One or more errors occurred. (0x80072EE2)
Inner exception: 0x80072EE2
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\lgtv\LgTvConnection.cs:line 258
2022-05-20 20:59:00.5439|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: status: Timeout, exception: One or more errors occurred. (0x80072EE2)
Inner exception: 0x80072EE2
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\lgtv\LgTvConnection.cs:line 258
2022-05-20 21:05:05.2401|DEBUG|ColorControl.LgService|Screensaver stopped, waking
```
</details>

The last line is suspicious, because I came back an hour after that event and the Windows screensaver was still engaged. There weren't any other messages related to the screensaver after this line, not even when I manually disengaged it with my inputs.

The "Screensaver stopped, waking" event at 21:05 seems like a phantom event that never actually happened. The PC was inactive at this point and I'm not sure what made ColorControl observe this. Even if something woke up the PC, ColorControl never registered the screensaver engaging again.

Ideas on how to debug?

**Comment by Maassoft** [comment]
Do you maybe have the power saving settings active that turn off the screen after a specific timeout? Of course it won't turn off our TV's, but maybe it will kill the screen saver because it stops the GPU from outputting anything. 
ColorControl is simply continuously checking whether the screen saver is still running, and if it's not it will wake the TV again.
By the way, what do you mean with "the PC was inactive at this point"? Was the PC sleeping?
