### ISSUE TITLE
Not able to open Ezadjust or Instart

### ISSUE THREAD

**Issue by ansu1997** [Maassoft/ColorControl#112]
![Capture](https://user-images.githubusercontent.com/61863889/178950615-f4a70149-4933-49c2-9c0d-bb6ace08216c.PNG)

I am able to auto select my tv from dropdown menu but functions like instant or ezadjust don't work. I have checked the options for advanced options too. Meanwhile the log displays a message like this:

2022-07-14 14:59:49.8238|ERROR|ColorControl.Services.LG.LgDevice|Error while launching app: Can't send message
Inner exception: 500 Application error
   at LgTv.LgTvApiCore.SendCommandAsync(String id, String message) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 156
   at LgTv.LgTvApiCore.SendCommandAsync(RequestMessage message) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 167
   at LgTv.LgTvApi.LaunchApp(String appId, Object params) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvApi.cs:line 599
   at CallSite.Target(Closure , CallSite , Object )
   at ColorControl.Services.LG.LgDevice.ExecutePreset(LgPreset preset, Boolean reconnect, LgServiceConfig config) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 481
   at LgTv.LgTvApi.LaunchApp(String appId, Object params) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvApi.cs:line 599
   at LgTv.LgTvApiCore.SendCommandAsync(RequestMessage message) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 166
   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 88
2022-07-14 14:59:50.0091|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV EG9A7V] Power state change: {}
2022-07-14 14:59:50.0091|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: the callback threw an exception: Object reference not set to an instance of an object.
   at ColorControl.Services.LG.LgDevice.PowerStateChanged(Object payload) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 371
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 259
2022-07-14 14:59:50.0091|ERROR|ColorControl.Services.LG.LgDevice|Error while connecting to 172.20.10.2: Can't send message
Inner exception: 404 no such service or method
   at LgTv.LgTvApiCore.SendCommandAsync(String id, String message) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 156
   at LgTv.LgTvApiCore.SubscribeAsync(RequestMessage message, Func`2 callback) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 180
   at LgTv.LgTvApi.SubscribePowerState(Func`2 callback, Object payload) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvApi.cs:line 502
   at ColorControl.Services.LG.LgDevice.Connect(Int32 retries) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 329
   at LgTv.LgTvApi.SubscribePowerState(Func`2 callback, Object payload) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvApi.cs:line 502
   at LgTv.LgTvApiCore.SubscribeAsync(RequestMessage message, Func`2 callback) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 180
   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 88
2022-07-14 14:59:50.0091|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made

Would appreciate some help from your side . Thank you.

**Comment by Maassoft** [comment]
A 500 Application error suggests that the tv is not handling the request very well. 
Your tv is a 2017 model? Maybe it's not supported on that model. Lowest model I have tested is a C8 (2018 model).
I see another error in your log, that's probably an error in ColorControl and I can try to fix that.

**Comment by ansu1997** [comment]
Yes mine is a 2017 model. Is there any way i could make it work with my tv or should i go for service remote ? I dont know whether the service remote i buy would work with the tv thats why i went with color control. Anyways please do let me know if theres any fix. Thank you

**Comment by Maassoft** [comment]
I don't know how to make it work with ColorControl. Your only options are a service remote or if you have an older Android phone laying around with an IR blaster, you could try some of the IR blaster apps. But those with access to the service menu are not free though.
