### ISSUE TITLE
Power management of the TV stopped working

### ISSUE THREAD

**Issue by chartreuse** [Maassoft/ColorControl#124]
Hello,
Everything was working fine but now I have problems, I don't know what could have caused it. Maybe a recent firmware update of the TV, a LG C2 42? Or that could be when I updated CC to 7.2. Not sure though, as I reverted back to 7.0 to no avail.

Here is the problem. The TV turns off according to the Windows Power Plan settings. For testing, I have set the TV to turn off after 1 minute of inactivity, see the log. If I move my mouse immediately after the TV turns off, it turns on normally.
But after a couple of minutes of idling, there is no way I can turn it on. It stays off. I think that as long as the "no Signal" picture is displayed, moving the mouse or pressing the keyboard wakes the TV. 
But if the screen is completely black (which happens after a certain amount of time of "no signal" message) then I can't wake up the TV.

Same problem when turning on the PC, the TV just stays off. no matter what. 

It is weird, as everything was working fine before!

If anyone has a suggestion, I'm all ears. Thank you!

Config: TV has a fixed IP, connected to the WiFi network. PC is connected via Ethernet. WOL option is enabled in the TV's settings under "Devices". usually I have a screensaver which fires after 1 min of idling, and the TV is set to turn off after 30 min of idle.

>  2022-08-28 11:04:02.6119|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:04:02.6119|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:04:02.6547|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:04:02.6547|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:04:02.6547|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:04:02.6547|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:04:11.1607|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"55","backlight":"90"}
2022-08-28 11:04:11.2091|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"100","brightness":"50","color":"60","backlight":80}
2022-08-28 11:04:16.0752|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 0
2022-08-28 11:04:24.2472|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2022-08-28 11:04:25.1329|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"60","backlight":90}
2022-08-28 11:04:25.2003|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":50,"backlight":30}
2022-08-28 11:05:28.5368|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"55","backlight":"90"}
2022-08-28 11:05:28.5923|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"100","brightness":"50","color":"60","backlight":80}
2022-08-28 11:05:30.1942|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"60","backlight":90}
2022-08-28 11:05:30.2638|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":50,"backlight":30}
2022-08-28 11:06:12.6140|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:06:12.6140|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:06:12.6656|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:06:12.6656|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:06:12.6656|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:06:12.6656|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:07:01.6480|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"55","backlight":"90"}
2022-08-28 11:07:01.6973|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"100","brightness":"50","color":"60","backlight":80}
2022-08-28 11:07:06.5414|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 0
2022-08-28 11:08:22.6020|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:08:22.6020|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:08:22.6327|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:08:22.6327|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:08:22.6327|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:08:22.6327|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:10:32.6039|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:10:32.6039|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:10:32.6248|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:10:32.6248|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:10:32.6248|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:10:32.6248|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:11:37.4928|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2022-08-28 11:11:38.3074|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"60","backlight":90}
2022-08-28 11:11:38.3762|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":50,"backlight":30}
2022-08-28 11:12:42.6159|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:12:42.6159|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:12:42.6501|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:12:42.6501|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:12:42.6608|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:12:42.6608|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:13:57.7924|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"55","backlight":"90"}
2022-08-28 11:13:57.8471|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] PictureSettingsChanged: {"contrast":"100","brightness":"50","color":"60","backlight":80}
2022-08-28 11:14:02.6558|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 0
2022-08-28 11:14:52.6005|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:14:52.6005|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:14:52.6251|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:14:52.6251|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:14:52.6251|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:14:52.6251|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:17:02.6000|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:17:02.6000|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:17:02.6142|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:17:02.6142|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:17:02.6142|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:17:02.6142|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:19:12.6023|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:19:12.6023|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:19:12.6135|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:19:12.6135|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:19:12.6135|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:19:12.6135|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:21:22.5978|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:21:22.5978|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:21:22.6304|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:21:22.6304|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:21:22.6304|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:21:22.6304|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:23:32.5994|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:23:32.5994|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:23:32.6191|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:23:32.6191|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:23:32.6191|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:23:32.6191|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:25:42.5985|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:25:42.5985|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:25:42.6151|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:25:42.6151|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:25:42.6151|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:25:42.6151|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:27:52.5961|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-08-28 11:27:52.5961|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:27:52.6111|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-08-28 11:27:52.6111|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:27:52.6111|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active"}
2022-08-28 11:27:52.6111|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-08-28 11:28:37.6016|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Power Off","onOff":"off","reason":"nosignal"}
2022-08-28 11:28:37.6016|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:37.6133|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Power Off Logo","onOff":"off","reason":"nosignal"}
2022-08-28 11:28:37.6133|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:40.7006|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Active Standby","onOff":"off","reason":"nosignal"}
2022-08-28 11:28:40.7006|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:40.7251|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active","processing":"Prepare Active Standby","onOff":"off","reason":"nosignal"}
2022-08-28 11:28:40.7251|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:40.7716|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active Standby"}
2022-08-28 11:28:40.7716|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:40.8112|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] ForegroundAppChanged: {"subscribed":true,"returnValue":true,"appId":"","processId":"","windowId":""}
2022-08-28 11:28:50.6060|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active Standby","processing":"Request Suspend","onOff":"off","reason":"oslbSaving"}
2022-08-28 11:28:50.6060|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:50.6312|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Active Standby","processing":"Prepare Suspend","onOff":"off","reason":"oslbSaving"}
2022-08-28 11:28:50.6312|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:28:51.8348|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C27LA] Power state change: {"returnValue":true,"state":"Suspend"}
2022-08-28 11:28:51.8348|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Manually, PoweredOffViaApp: False
2022-08-28 11:29:40.8051|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: status: Timeout, exception: One or more errors occurred. (0x80072EE2)
Inner exception: 0x80072EE2
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 259
2022-08-28 11:33:51.1128|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2022-08-28 11:33:57.6814|ERROR|ColorControl.Services.NVIDIA.NvService|Error while getting displays: The request is not supported.
   at ColorControl.ScreenInterrogatory.GetAllMonitorsFriendlyNames()+MoveNext() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Native\ScreenInterrogatory.cs:line 289
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at ColorControl.ScreenInterrogatory.DeviceFriendlyName(Screen screen) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Native\ScreenInterrogatory.cs:line 308
   at ColorControl.Services.NVIDIA.NvService.GetDisplayInfos() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvService.cs:line 608
```

**Comment by Maassoft** [comment]
I'm not sure how to fix your problem, but if you can, can you try a wired connection?
I've been using WiFi on my C9 for a couple of months now, but turning the TV on only works like 50% of the time. With a wired connection if worked 99% of the time. I've even tried the "LG TV Plus" app on my phone in such occasions (which can send a WOL package too), but the TV wouldn't turn on then as well.
And I'm not entirely sure what you mean with the TV turned off but it's still showing a "No signal message"? Maybe you have multiple screen savers active: one after 1 minute that stops the GPU sending a signal and one that really turns off the TV later?

**Comment by chartreuse** [comment]
I've delved into the problem and I stumbled upon an option in the service menu which prevents the TV to completely turn off after 15 minutes of no signal status (It's called "15Min Force Off" in "System 1" menu). 

With this option disabled, the TV stays on a "No Signal" status as long as nobody wakes the PC, and I can wake the PC without problem so that's a good thing, and I'd say the most part of the issue is solved. 

But as to why the keyboard/mouse don't wake up the PC when the TV is turned off seems odd to me. My PC is set to never go to sleep mode, so it should not make any difference if the TV is turned off or on.

As to the other part of the problem, no, the TV doesn't turn on anymore when the PC is booting. I have to use the remote. I have try the LG app (which is named LG ThinQ here) and it works perfectly manually, but it kills the purpose of this app which is to use the TV as a normal monitor without external input needed.

Anyway I'll try a wired connection as you suggested as I think WiFi may be the culprit here.

> And I'm not entirely sure what you mean with the TV turned off but it's still showing a "No signal message"? Maybe you have multiple screen savers active: one after 1 minute that stops the GPU sending a signal and one that really turns off the TV later?

Sorry if I'm not clear, I'll try to sum it up here:
Under normal operation: my PC is set to display a screensaver after 1 minute of idling. Then the screen is set to turn off after 30 minutes (according to Win10 power plan settings)
So if I let my PC alone: 
0 min: desktop, idle
1 min: screensaver is on
30 min: Black screen with No Signal is displayed (_I don't know why it says it has no signal because my PC is set to NEVER go to sleep...so there should be a signal_) _(In this state, it can be awaken)_
(_if the option 15Min Force Off is enabled_) 45 min : TV turns off completely, red LED is on, TV cannot be awaken by mouse or keyboard.

**Comment by combineclub** [comment]
This has begun affecting me too just like you described. 

I’ve had flawless, automated TV on/off automation with ColorControl since first installation a few months back. I’ve updated CC now and again and there has been one firmware update via LG; it be recent Windows 11 updates? `Nvidia?!`

**Comment by farnoy** [comment]
I think I'm also affected by this or something similar, but it's not easy to narrow down the cause.

I have C1 & G1 plugged in over HDMI. I use ColorControl to turn these on/off with the screensaver, I don't power off the desktop computer they are attached to. Both of these TVs are firewalled on my network so I haven't done a firmware update for a long while (but WoL packets are allowed through the FW, more on this in a bit). I've been on Windows 11 21H2 for months so that hasn't changed either.

I have changed Nvidia GPUs and drivers in the recent weeks, so that's something to suspect.

Things I've tried:

* Multiple versions of ColorControl - I was using 7.3.0.0 until last week and it worked perfectly fine for a long time until it stopped turning off the TVs. I tried upgrading to 8.2.0.0 but it doesn't change anything.
* The WakeOnLan test in "Test power on/off" - this has been working and continues to work flawlessly, which makes me want to rule out the new elevated process / service changes in CC as unnecessary in my case.  @chartreuse @combineclub Does this test continue to work for you despite other issues? Is it something our setups have in common?
* `powercfg -requests` but it only shows the NVidia HDMI audio driver there. I don't have a saved output of this command from when CC worked with WoL, but I'm 90% sure it always showed up there and never prevented the screensaver from activating

One observation that might be relevant @Maassoft - I am seeing a different message when the screensaver is detected compared to older logs that I posted here on GitHub in the past:

Currently, I am seeing this:
```
2022-12-13 02:18:14.2898|DEBUG|ColorControl.Services.LG.LgService|Screensaver started: scrnsave.scr, but invalid parent: rundll32
2022-12-13 02:18:26.5736|DEBUG|ColorControl.Services.LG.LgService|Screensaver started: scrnsave.scr, but invalid parent: rundll32
2022-12-13 02:19:51.4506|DEBUG|ColorControl.Services.LG.LgService|Process monitor: TV(s) where connected, but not any longer
2022-12-13 02:19:51.5438|DEBUG|ColorControl.Services.LG.LgDevice|[LG salon TV] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2022-12-13 02:19:51.5438|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-12-13 02:19:51.5703|DEBUG|ColorControl.Services.LG.LgDevice|[LG salon TV] PictureSettingsChanged: {"contrast":"85","backlight":"10","brightness":"50","color":50}
2022-12-13 02:19:51.5894|DEBUG|ColorControl.Services.LG.LgDevice|[LG salon TV] ForegroundAppChanged: {"appId":"com.webos.app.hdmi2","subscribed":true,"returnValue":true,"windowId":"","processId":""}
2022-12-13 02:19:51.6471|DEBUG|ColorControl.Services.LG.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Power Off","onOff":"off","reason":"remoteKey"}
... <CUT - a bunch of intermediate state transitions>
2022-12-13 02:19:51.7883|DEBUG|ColorControl.Services.LG.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Prepare Suspend","onOff":"off","reason":"remoteKey"}
2022-12-13 02:19:51.7883|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: App, PoweredOffViaApp: True
```

It's as if CC thinks it suspended the TV, but I can tell it's still on because the standby light is not showing and it's immediately responsive when I end the Windows screensaver with input.

But when I reported an issue previously in #96, the log said:

```
2022-04-23 23:20:51.0576|DEBUG|ColorControl.LgService|Screensaver started: scrnsave.scr, parent: winlogon
2022-04-23 23:20:51.0576|DEBUG|ColorControl.LgService|Screensaver check: test connection with LG salon TV...
```

Could that be what's preventing CC from powering off the TV when it's capable of doing so? When I end the screensaver, I do see logs about it sending a WoL packet, which I assume would work if the TV was off in the first place.
