### ISSUE TITLE
Connection Aborted Error 

### ISSUE THREAD

**Issue by Haven-Lau** [Maassoft/ColorControl#130]
Ever since I updated the TV firmware and CC I've been getting this error:
```
2022-09-30 15:47:33.4111|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] PictureSettingsChanged: {"contrast":"85","brightness":"50","color":"55","backlight":"30"}
2022-09-30 15:56:10.8271|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 15:58:20.7976|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-09-30 15:58:20.7976|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 15:58:20.8254|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-09-30 15:58:20.8254|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 15:58:20.8254|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active"}
2022-09-30 15:58:20.8254|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 16:00:30.7878|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-09-30 16:00:30.7878|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active"}
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 16:01:27.9337|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: status: ConnectionAborted, exception: One or more errors occurred. (0x80072EFE)
Inner exception: 0x80072EFE
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 259
2022-09-30 22:02:24.2479|ERROR|LgTv.LgTvApiCore|SendMessageAsync: The object has been closed. (0x80000013)
2022-09-30 22:02:24.2622|ERROR|LgTv.LgTvApiCore|SendMessageAsync: The object has been closed. (0x80000013)
```

Does anyone have any idea what would be causing this? It was connected and working fine until:

```
2022-09-30 16:00:30.7878|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
2022-09-30 16:00:30.7878|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2AUA] Power state change: {"returnValue":true,"state":"Active"}
2022-09-30 16:00:30.8191|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False```

any help is appreciated, thanks!

**Comment by Maassoft** [comment]
I'm not entirely sure what's causing this. It's normal to see those exceptions after the TV is power off, but in your case it happens after power on? And after the error you can no longer control the TV via CC?
You've indicated that you've updated CC as well, what happens if you try out an older version?

**Comment by Haven-Lau** [comment]
With the older version it won't turn off my TV when I sleep my computer, but then the next time I turn my computer and the TV back on manually, it will then shut the TV off, it's like the sleep packet is cached but didn't go through and gets sent on the next boot cycle, it's really strange.
