### ISSUE TITLE
8.2.0.0 fails silently with Exception e0434352 - unhandled exception?

### ISSUE THREAD

**Issue by farnoy** [Maassoft/ColorControl#150]
Hi, I've upgraded from 7.3.0.0 to 8.2.0.0 and the first thing I noticed is that it doesn't start. Nothing in the logs, I wiped the entire config directory but it crashes before initializing a window.

I tried running it from the command line, no output. After clearing the Roaming AppData folder, it creates Maassoft/ColorControl/8.2.0.0 (empty folder) and crashes. No output log is created in this directory, the app dies before it's able to communicate anything.

Some data from WinDbg (I don't know CLR but hopefully you'll find it useful):

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff7b2f428c (KERNELBASE!RaiseException+0x000000000000006c)
   ExceptionCode: e0434352 (CLR exception)
  ExceptionFlags: 00000081
NumberParameters: 5
   Parameter[0]: ffffffff80131509
   Parameter[1]: 0000000000000000
   Parameter[2]: 0000000000000000
   Parameter[3]: 0000000000000000
   Parameter[4]: 00007fff4d400000

PROCESS_NAME:  ColorControl.exe

EXCEPTION_CODE_STR:  80131509

FAULTING_THREAD:  ffffffff

STACK_TEXT:  
00000000`001ce3e0 00007fff`77344a3b System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounterLib.GetStringTable+0x1cb
00000000`001ce470 00007fff`77341d38 System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounterLib.get_NameTable+0x48
00000000`001ce4c0 00007fff`77341ac3 System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounterLib.get_CategoryTable+0x2a3
00000000`001ce5b0 00007fff`77342445 System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounterLib.CounterExists+0x25
00000000`001ce610 00007fff`77342312 System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounterLib.CounterExists+0x42
00000000`001ce670 00007fff`7733f290 System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounter.InitializeImpl+0x80
00000000`001ce6e0 00007fff`7733e920 System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounter..ctor+0xd0
00000000`001ce740 00007ffe`ede11e9c ColorControl!ColorControl.Common.ProcessExtensions.FindIndexedProcessName+0x17c
00000000`001ce8e0 00007ffe`edd47929 ColorControl!ColorControl.Common.ProcessExtensions.Parent+0x49
00000000`001ce930 00007ffe`edd30192 ColorControl!ColorControl.Program.Main+0x92


STACK_COMMAND:  ** Pseudo Context ** ManagedPseudo ** Value: ffffffff ** ; kb

SYMBOL_NAME:  System_Diagnostics_PerformanceCounter!System.Diagnostics.PerformanceCounterLib.GetStringTable+1cb

MODULE_NAME: System_Diagnostics_PerformanceCounter

IMAGE_NAME:  System.Diagnostics.PerformanceCounter.dll
```

**Comment by Maassoft** [comment]
Thanks for the bug report. Somehow ColorControl encounters an exception on your system while looking up the parent process of itself. I will make the code more robust in the next update.

**Comment by farnoy** [comment]
Thanks, I googled for `PerformanceCounterLib.GetStringTable` and arrived at https://github.com/dotnet/runtime/issues/38756 which links to: https://learn.microsoft.com/en-US/troubleshoot/windows-server/performance/manually-rebuild-performance-counters

Supposedly, they updated CLR to show warnings when this is the case, but I'm not sure why it didn't happen for me.

I have no idea how I corrupted my performance counters or why that is even possible, but following the rebuild steps fixed the issue. The guide also lists a different symptom that I could reproduce - `perfmon.exe` shows some warnings at the start when the counters are corrupt.

**Comment by CrazyEyesDave** [comment]
I have the same issue.
8.2.0.0 doesn't start (i see the exe in task manager but it closes immediately)
7.3.0.0 works fine

unable to rebuild performance counter setting for some reason, working on it

**Comment by lordbordem** [comment]
Likewise, I've been having a similar issue since 8.0.0.0. 7.3.0.0 still works fine but anything newer won't launch at all. 
Event viewer shows the following error event when I try to launch 8.2.0.0

```
Application: ColorControl.exe
CoreCLR Version: 6.0.1222.56807
.NET Version: 6.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Instance 'ColorControl' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at ColorControl.Common.ProcessExtensions.FindIndexedProcessName(Int32 pid, String processName, IEnumerable`1 processes) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\ProcessExtensions.cs:line 19
   at ColorControl.Common.ProcessExtensions.Parent(Process process, IEnumerable`1 processes) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\ProcessExtensions.cs:line 45
   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 48
```
This is on the latest version of Windows 11 but it was doing the same thing on Windows 10 on the same computer. I've tried rebuilding the performance counters but that doesn't fix it.
