### ISSUE TITLE
Bitdefender sees ColorControl 8.3.0.0 as malware

### ISSUE THREAD

**Issue by vikdean** [Maassoft/ColorControl#162]
Interestingly it only triggers when I try to use the blank screensaver shortcut.
 
```
Bitdefender detected potentially malicious behavior and blocked all applications involved.
Detection ID: SuspiciousBehavior.BF9116AC4A642C05
```
It worked fine with 8.2.0.0

**Comment by Maassoft** [comment]
Weird, I have no problems with Windows Defender. I suspect it's just a false positive (the blank screensaver functionality hasn't been changed for a while).

**Comment by vikdean** [comment]
Yeah, something broke...
```
2023-01-08 15:03:30.1309|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-01-08 15:03:30.1309|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
2023-01-08 15:03:31.1343|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C21LA...
```
The "power on" function is the only thing that works now... I even tried to roll back to 8.2.0.0; added the folder, the .exe as an exception in Bitdefender, but nothing...

**Comment by vikdean** [comment]
I've tried clearing out the settings in AppData, but no no avail.

This is what I get from 8.3.0.0:
```
2023-01-08 23:01:58.9905|ERROR|ColorControl.Common.PipeUtils|PipeUtils.SendMessage|System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at ColorControl.Common.PipeUtils.SendMessage(String message) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\PipeUtils.cs:line 18
```

And this from 8.2.0.0:
![image](https://user-images.githubusercontent.com/16238514/211221376-14fbbf37-82c2-435e-8136-38adf0527ddf.png)

**Comment by antnyhills** [comment]
![image](https://user-images.githubusercontent.com/10813364/219468836-1ae63c90-28b3-41d3-9257-4cfa127ba384.png)


Looks like I'm getting a similar issue, also have Bitdefender Endpoint Security on my device
