### ISSUE TITLE
Error applying overclock with nvidia

### ISSUE THREAD

**Issue by AeliusSaionji** [Maassoft/ColorControl#217]
Hello! I'm having trouble with applying an overclock preset. Let me know if you need more information.

---

Color Control release: 9.2.0.0

Desired settings as set by Afterburner or EVGA Precision X: 
Stock Curve, +180 offset, max 1800MHz, max 850mV
![image](https://user-images.githubusercontent.com/4342746/235290077-537e8c13-1214-4fa9-98ce-e72655bc9bf6.png)

---

Color control sees this:
![image](https://user-images.githubusercontent.com/4342746/235290112-696f92a5-3e90-4ff2-9403-ad142754e0d1.png)

---

Attempted settings in ColorControl
![image](https://user-images.githubusercontent.com/4342746/235289627-189a1a28-c55d-4e78-9a18-177df6b238dc.png)

---

Error log:

```log
2023-04-29 03:17:44.4972|ERROR|ColorControl.Common.PipeUtils|PipeUtils.SendMessage|System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at ColorControl.Common.PipeUtils.SendMessage(String message, Int32 timeout) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\PipeUtils.cs:line 18
```

**Comment by Maassoft** [comment]
Do you have the service running? Applying an overclock requires the app to run as administrator or set the "Elevation-method" on the Options-tab to "Use Windows Service".

**Comment by AeliusSaionji** [comment]
Ah, that makes sense.
But I'm also getting an error for the service.

```log
2023-04-29 23:29:57.9136|DEBUG|ColorControl.Program|Using data path: C:\Users\aelius\AppData\Roaming\Maassoft\ColorControl
2023-04-29 23:29:58.8782|ERROR|ColorControl.Program|Unhandled exception: Cannot start service 'Color Control Service' on computer '.'.
Inner exception: The service did not respond to the start or control request in a timely fashion.
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at ColorControl.Common.Utils.StartService() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\Utils.cs:line 915
   at ColorControl.Program.HandleStartupParams(StartUpParams startUpParams, Process existingProcess) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 263
   at ColorControl.Program.MainAsync(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 101
   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 46
   at ColorControl.Program.GlobalUnhandledExceptionHandler(Object sender, UnhandledExceptionEventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 401
   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 46
```

**Comment by Maassoft** [comment]
It seems that the service is not able to start. Can you set Elevation method to "None" and then back to "Use Windows Service"?
If it still does not work, what happens if you manually start the service via "services.msc" (open "Color Control Service" and press "Start")?
Otherwise, try running as "administrator" and if the above steps work in that case.

**Comment by AeliusSaionji** [comment]
Manually running as admin does allow the nvidia oc to apply.

No amount of fussing on my end seems to get the service to work, though.
