### ISSUE TITLE
Error launching service.

### ISSUE THREAD

**Issue by Prouk** [Maassoft/ColorControl#218]
When trying to install / launch the windows service, getting the error : 

`2023-04-30 15:45:13.1324|ERROR|ColorControl.Program|Exception in thread: Cannot start service 'Color Control Service' on computer '.'.
Inner exception: Le service n’a pas répondu assez vite à la demande de lancement ou de contrôle.
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at ColorControl.Common.Utils.StartService() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\Utils.cs:line 915
   at ColorControl.Common.Utils.InstallService() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\Utils.cs:line 975
   at ColorControl.MainForm.SetElevationMethodUseService() in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 1225
   at ColorControl.MainForm.SetElevationMethod(ElevationMethod elevationMethod) in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 1190
   at ColorControl.MainForm.rbElevationNone_CheckedChanged(Object sender, EventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 1177
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at ColorControl.Program.GlobalThreadExceptionHandler(Object sender, ThreadExceptionEventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 406
   at ColorControl.Program.MainAsync(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 143
   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 46`
   
"Le service n’a pas répondu assez vite à la demande de lancement ou de contrôle." = "Error 1053 the service did not respond to the start or control request in a timely fashion"

- Running W11 insider dev channel
- Running on the .Net framework required by the soft
- Timeout for service already set to 3 minutes
- Already uninstalled / reinstalled .Net (tried with multiple versions)
- Already checked binPath

I'm there if you need more details

**Comment by Maassoft** [comment]
I've re-installed the service on my PC (set Elevation method to "None" and back to "User Windows Service" again) and I did not get that error here. Was ColorControl running as admininstrator? It should not be needed, but maybe "User Account Control" prevents it from installing correctly (I've disabled that here). What happens if you go to "services.msc" and start the "Color Control Service" manually?
Otherwise, maybe it's because of W11 insider version?

**Comment by Prouk** [comment]
Got it to work, finally.
So, i'm still on the latest insider build (but not connected to the microsoft account)
Switched to a local account ( important step I think ), and finished some other windows update I had going.
Can almost confirm that it runs on every build, but that the account privilege are messed up by the linking.

**Comment by AeliusSaionji** [comment]
I am getting this error and have not been able to fix it-

Regular release W11 Pro
