### ISSUE TITLE
Error launching CC after new update

### ISSUE THREAD

**Issue by bel57** [Maassoft/ColorControl#224]
Hello

Updated to latest version of ColorControl and I get the following error, can you please help/fix it?
It looks like you left some direct path dependent of your username/local files (C:\Users\vinni\source\repos\ColorControl)
```

---------------------------
Error
---------------------------
Error while initializing application: C:\WINDOWS\system32\ColorControl.exe

   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)

   at ColorControl.MainForm.InitInfo() in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 358

   at ColorControl.MainForm..ctor(AppContextProvider appContextProvider, PowerEventDispatcher powerEventDispatcher, ServiceManager serviceManager) in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 135

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

   at ColorControl.Program.MainAsync(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 142

   at ColorControl.Program.Main(String[] args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Program.cs:line 46
---------------------------
OK   
---------------------------

```

**Comment by Maassoft** [comment]
I think this might be caused by the install location, which seems to be the system folder of Windows. I don't think it's a good idea to install the app there, or did you not do this? 
Btw, you can ignore the paths with my username, these are useful for debugging purposes (they point to the source files on the development machine, the application doesn't need them).

**Comment by bel57** [comment]
Hey there, thanks for looking into it.
I didn't do anything. I used to update the software manually via github releases but then when you added the auto updater I left the tool do the job. There is no such exe in System32, hence the bug. Something wrong with the new code in the latest build.
Here are the files location:
![image](https://github.com/Maassoft/ColorControl/assets/10614811/267d52bf-7eee-4dc8-8978-e63e59c3f7ee)

**Comment by Maassoft** [comment]
The service is responsible for downloading the new update and updating the files in the location where it is installed, hence you're seeing the files there (it unzips the files there, before copying them).
But maybe your scheduled task isn't configured properly and the "Start in" location is empty or wrong. It should contain the directory the app is installed into (in your case C:\Users\Bel\ColorControl):
![image](https://github.com/Maassoft/ColorControl/assets/70057942/0399c180-7533-43e5-9b39-3978a8a2e54a)

You can also just uncheck/check "Automatically start after login" and it should fix the location.
I've just tested an update from earlier 9.x version to 9.4 in a virtual W11 environment and it is working as it should there.

**Comment by bel57** [comment]
Ok so I unchecked/checked that setting and the task looks the same as yours.
![image](https://github.com/Maassoft/ColorControl/assets/10614811/87dafbee-78ae-4d80-bb55-99bb55c654c1)

HOWEVER closing the program and running it from my user directory still throws the very same error:
![image](https://github.com/Maassoft/ColorControl/assets/10614811/89957544-6abf-409d-a469-c105c978586b)

I've narrowed down the error. It's only happening on launch when I fire the exe from the start menu (Startisback).
When I launch it from windows explorer or a shortcut on my desktop, it works fine.

Why all the at Microsoft.Extensions.DependencyInjection.ServiceLookup and  at ColorControl.Program.Main errors?
Btw that's new behavior, I've always launched CC from shortcut and from Start menu.

**Comment by Maassoft** [comment]
Ahh, so you're starting CC from a custom shortcut? Maybe the "Start in" field is empty, so the working directory is probably C:\Windows\system32 then. Be sure to fill in the field like below (in your case C:\Users\Bel\ColorControl):

![image](https://github.com/Maassoft/ColorControl/assets/70057942/4671c6a6-4621-45f4-8147-b79819f4f97a)

If I leave it empty I get the same error. It is possible the behavior changed and I think I could change this by always looking at the location of ColorControl.exe and not being dependent on what Windows provides.

**Comment by bel57** [comment]
My shortcut already has that field filed in, no problem. It's when launching the exe directly from Start Menu that I get the error. I guess there's some argument missing so the exe (and not shortcut) launched from Start menu search is trying to launch from System32. Not a big deal but that could be worth investigating as it's a new behavior. Thanks again for looking into it.

**Comment by BoredErica** [comment]
When I try to open ColorControl in any way but going to the folder and double clicking, I get the same error. This includes VBS or AHK script. EG: 
run C:\Program Files (x86)\ColorControl\ColorControl.exe

causes an error message.
