### ISSUE TITLE
Nvidia tab not showing

### ISSUE THREAD

**Issue by Kas152** [Maassoft/ColorControl#229]
Hi guys,

I just read the release notes from the latest update (9.5.0.0) and wanted to try out the new novideo function for the nvidia controller. You have to do this under the nvidia tab, but this is not showing in my case. I have a nvidia Geforce gtx 1650, so I assume this should work? I can however acces the dithering options and they work nicely. Also, I have the option turned on that should show the nvidia tab. Furthermore, there is an option for nvidia settings when right clicking on the tray icon of color control, but if I select any option there I get this message: Exception in thread: Object reference not set to an instance of an object. I'm using a LG C2. Could you guys shed some light on this? Many thanks in advance.

**Comment by Maassoft** [comment]
Can you check the Log tab? Maybe there's an exception while executing (a specific portion of) the Nvidia controller/API, which results in hiding the Nvidia tab.
A certain hardware/software (driver) combination might be causing this.

**Comment by Maassoft** [comment]
I don't see the initialization of NVIDIA anywhere in your log. Can you clear the log, restart ColorControl and then check the "Main application" log? It should show lines likes this:

```
2023-05-26 21:49:15.3504|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-05-26 21:49:17.5303|DEBUG|ColorControl.MainForm|Initializing NVIDIA...Done.
```

Except in your case the second line could contain an error.

**Comment by Kas152** [comment]
Hi, it shows this:

2023-05-27 10:16:33.4781|DEBUG|ColorControl.MainForm|Initializing NVIDIA...

2023-05-27 10:16:33.9376|DEBUG|ColorControl.MainForm|Initializing NVIDIA...Done.

2023-05-27 10:16:35.1890|DEBUG|ColorControl.MainForm|No NVIDIA device detected: Object reference not set to an instance of an object.

at ColorControl.Services.NVIDIA.NvGpuInfo.GetPowerUsageInMilliWatts() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvGpuInfo.cs:line 248

at ColorControl.Services.NVIDIA.NvGpuInfo.ToString() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvGpuInfo.cs:line 370

at ColorControl.Services.NVIDIA.NvPanel.RefreshNvGpuInfo() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvPanel.cs:line 1416

at ColorControl.Services.NVIDIA.NvPanel.cbxNvGPU_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvPanel.cs:line 1401

at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)

at ColorControl.Services.NVIDIA.NvPanel.UpdateNvGpuInfo(List`1 gpus) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvPanel.cs:line 183

at ColorControl.Services.NVIDIA.NvPanel.UpdateDisplayInfoItems() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvPanel.cs:line 170

at ColorControl.Services.NVIDIA.NvPanel.FillNvPresets() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvPanel.cs:line 107

at ColorControl.Services.NVIDIA.NvPanel..ctor(NvService nvService, NotifyIcon trayIcon, IntPtr handle, AppContextProvider appContextProvider) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvPanel.cs:line 47

So that means it cannot find it and I have to tell it somehow that it is in fact there?

Van: Maassoft ***@***.***>
Verzonden: vrijdag 26 mei 2023 22:23
Aan: Maassoft/ColorControl ***@***.***>
CC: Kas152 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Maassoft/ColorControl] Nvidia tab not showing (Issue #229)

I don't see the initialization of NVIDIA anywhere in your log. Can you clear the log, restart ColorControl and then check the "Main application" log? It should show lines likes this:

2023-05-26 21:49:15.3504|DEBUG|ColorControl.MainForm|Initializing NVIDIA...

2023-05-26 21:49:17.5303|DEBUG|ColorControl.MainForm|Initializing NVIDIA...Done.

Except in your case the second line could contain an error.

**Comment by Maassoft** [comment]
Thanks for the log. I think there's an error in ColorControl when reading the GPU power usage on your particular system.
I will try to fix it in the next release.

**Comment by Kas152** [comment]
Much appreciated!! 👍🏻

-------- Oorspronkelijk bericht --------
Op 29 mei 2023 16:04, schreef Maassoft :

**Comment by Battler624** [comment]
I am having the exact same issue but I assume its because I used NVCleanstall recommended settings (along with MSI adjustments)

https://www.techpowerup.com/download/techpowerup-nvcleanstall/

**Comment by Kas152** [comment]
Interesting piece of software you have there. I have not used it with my nvidia installation so I presume that this will not be the cause of the issue?

Van: Battler624 ***@***.***>
Verzonden: zaterdag 10 juni 2023 15:46
Aan: Maassoft/ColorControl ***@***.***>
CC: Kas152 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Maassoft/ColorControl] Nvidia tab not showing (Issue #229)

I am having the exact same issue but I assume its because I used NVCleanstall recommended settings (along with MSI adjustments)

https://www.techpowerup.com/download/techpowerup-nvcleanstall/

**Comment by HeyJoplin** [comment]
Hi, I'm having a similar issue:

```
|ERROR|ColorControl.Services.NVIDIA.NvGpuInfo|System.NullReferenceException: Object reference not set to an instance of an object.
   at ColorControl.Services.NVIDIA.NvGpuInfo.<GetPowerUsageInMilliWatts>b__62_0() in .\Services\NVIDIA\NvGpuInfo.cs:line 173
   at NLog.Logger.Swallow[T](Func`1 func, T fallback)
```
