### ISSUE TITLE
Can't connect to LG C2

### ISSUE THREAD

**Issue by MrFutureV** [Maassoft/ColorControl#232]
IP and MAC are right,it was shows connecting sign on the TV when i started the software and i pressed ok,but it just can't connect somehow,custom dont work either,firmware 03.33.16
![20230529003828](https://github.com/Maassoft/ColorControl/assets/46783891/1aea5424-585c-4f93-9b01-6c3e37bc88ab)

**Comment by MrFutureV** [comment]
here is the log
2023-05-29 00:37:28.5520|DEBUG|ColorControl.Program|Using data path: C:\Users\pkwl5\AppData\Roaming\Maassoft\ColorControl
2023-05-29 00:37:28.9906|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-05-29 00:37:29.2751|DEBUG|ColorControl.Services.Common.ServiceBase`1|Reverting to default presets
2023-05-29 00:37:29.2751|DEBUG|ColorControl.MainForm|Initializing NVIDIA...Done.
2023-05-29 00:37:30.1869|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL_Main_Control_Create
2023-05-29 00:37:30.1869|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL2_Main_Control_Create
2023-05-29 00:37:30.1869|DEBUG|ColorControl.MainForm|No AMD device detected
2023-05-29 00:37:30.1920|DEBUG|ColorControl.Services.Common.ServiceBase`1|Reverting to default presets
2023-05-29 00:37:30.3362|DEBUG|ColorControl.Services.Common.ServiceBase`1|Reverting to default presets
2023-05-29 00:37:30.8299|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: On
2023-05-29 00:37:30.8299|DEBUG|ColorControl.Services.LG.LgService|PowerModeChanged: MonitorOn
2023-05-29 00:37:31.7620|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.3:3001
2023-05-29 00:37:33.2073|DEBUG|ColorControl.Forms.FormUtils|Detected NotificationState change from 0 to QUNS_BUSY
2023-05-29 00:37:42.1794|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2PCA] Power state change: {"state":"Active","subscribed":true,"returnValue":true}
2023-05-29 00:37:42.1794|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2023-05-29 00:37:42.1943|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2PCA] PictureSettingsChanged: {"brightness":50,"contrast":85,"color":50,"backlight":100}
2023-05-29 00:37:42.1943|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C2PCA] ForegroundAppChanged: {"subscribed":true,"returnValue":true,"appId":"com.webos.app.hdmi3","processId":"","windowId":""}
2023-05-29 00:37:55.0735|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:37:55.0829|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:37:55.5918|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:37:56.1055|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:20.6472|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:20.6472|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:21.1666|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:21.6819|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:22.1883|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:22.1883|ERROR|ColorControl.Services.LG.LgPanel|System.InvalidOperationException: Not connected
   at ColorControl.Services.LG.LgDevice.CheckConnectionAsync() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 772
   at ColorControl.Services.LG.LgDevice.GenericPictureAction(Dictionary`2 parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 1097
   at ColorControl.Services.LG.LgDevice.ExecuteActionAsync(InvokableAction action, String[] parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 743
   at ColorControl.Services.LG.LgPanel.btnLgExpertColorGamut_Click(Object sender, EventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgPanel.cs:line 975
2023-05-29 00:38:25.1483|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C2PCA...
2023-05-29 00:38:25.1483|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:25.1483|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:25.6583|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:25.6583|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
2023-05-29 00:38:26.6736|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C2PCA...
2023-05-29 00:38:26.6736|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:26.6736|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:27.1821|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:27.1821|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
2023-05-29 00:38:28.1982|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C2PCA...
2023-05-29 00:38:28.1982|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:28.1982|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:28.7071|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:28.7071|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
2023-05-29 00:38:29.7224|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C2PCA...
2023-05-29 00:38:29.7224|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:29.7224|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:30.2319|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:30.2319|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
2023-05-29 00:38:31.2460|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C2PCA...
2023-05-29 00:38:31.2460|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:31.2517|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:31.7592|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:31.7592|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
2023-05-29 00:38:33.7991|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C2PCA...
2023-05-29 00:38:33.7991|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: ws://192.168.1.3:3000
2023-05-29 00:38:33.7991|ERROR|LgTv.LgTvApiCore|Connect to ws://192.168.1.3:3000/: 0x80072EFF
2023-05-29 00:38:34.3083|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-05-29 00:38:34.3083|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False

**Comment by MrFutureV** [comment]
works perfectly fine with LGTV companion tho

**Comment by Maassoft** [comment]
Have you tried setting the "Use secure connection" option? LG disabled the support for unsecure connections via a firmware update a couple of months ago.

**Comment by MrFutureV** [comment]
> Have you tried setting the "Use secure connection" option? LG disabled the support for unsecure connections via a firmware update a couple of months ago.

ohh,yeah it works fine when i enabled "Use secure connection" option,thx a lot,and one more question is that ,when i switch the TV to game optimizer mode and go expert to change peak brightness to high，will this only affect the game optimizer mode or all modes ？

**Comment by MrFutureV** [comment]
and expert option changes are once for all,or i have to have color option on everytime i want it to work?

**Comment by Maassoft** [comment]
The expert options only change the active picture mode, not other modes. The chosen setting should remain active in that mode, though, so you'll only have to change it once per mode.

**Comment by allan1096** [comment]
> > Have you tried setting the "Use secure connection" option? LG disabled the support for unsecure connections via a firmware update a couple of months ago.
> 
> ohh,yeah it works fine when i enabled "Use secure connection" option,thx a lot,and one more question is that ,when i switch the TV to game optimizer mode and go expert to change peak brightness to high，will this only affect the game optimizer mode or all modes ？

where do i find the "use secure connection" option ?

**Comment by Amoeba00** [comment]
> > > Have you tried setting the "Use secure connection" option? LG disabled the support for unsecure connections via a firmware update a couple of months ago.
> > 
> > 
> > ohh,yeah it works fine when i enabled "Use secure connection" option,thx a lot,and one more question is that ,when i switch the TV to game optimizer mode and go expert to change peak brightness to high，will this only affect the game optimizer mode or all modes ？
> 
> where do i find the "use secure connection" option ?

LG Controller tab - last option

![image](https://github.com/Maassoft/ColorControl/assets/39176113/558de7ad-c4aa-4879-92f4-669ec46925f8)
