### ISSUE TITLE
error while connecting

### ISSUE THREAD

**Issue by speedboattoyota** [Maassoft/ColorControl#255]
The app can detect my tv but I seem to have an error while connecting. The expert functions don't work.

Please see the log below:

Error while connecting to 192.168.2.6: Can't send message
Inner exception: 500 Application error
   at LgTv.LgTvApiCore.SendCommandAsync(String id, String message) in .\LgTv\LgTvConnection.cs:line 147
   at LgTv.LgTvApiCore.SubscribeAsync(RequestMessage message, Func`2 callback) in .\LgTv\LgTvConnection.cs:line 173
   at LgTv.LgTvApi.SubscribePictureSettings(Func`2 callback, Object payload) in .\LgTv\LgTvApi.cs:line 631
   at ColorControl.Services.LG.LgDevice.Connect(Int32 retries) in .\Services\LG\LgDevice.cs:line 407
   at LgTv.LgTvApi.SubscribePictureSettings(Func`2 callback, Object payload) in .\LgTv\LgTvApi.cs:line 631
   at LgTv.LgTvApiCore.SubscribeAsync(RequestMessage message, Func`2 callback) in .\LgTv\LgTvConnection.cs:line 173
   at LgTv.LgTvApiCore.SendCommandAsync(String id, String message) in .\LgTv\LgTvConnection.cs:line 143
   at ColorControl.Program.MainAsync(String[] args) in .\Program.cs:line 149
   at ColorControl.Program.Main(String[] args) in .\Program.cs:line 48

**Comment by Maassoft** [comment]
What TV are you using? It seems the TV throws an error while subscribing to picture setting changes.
I could make this optional or ignore the error when it occurs, but there might be more issues.
