### ISSUE TITLE
C8 can't connect / log attached

### ISSUE THREAD

**Issue by slurpentyne** [Maassoft/ColorControl#271]
Tried latest and 8.5 versions. Tried all 3 elevation methods for each. Tried ethernet and wifi connections and made sure devices showing in Device Manager matched IP/MAC. Tried manually adding. Running as administrator. Removing [LG] filter allowed TV to show in auto detect drop down menu, but nothing occurs at that point. Attempting to change a setting produces error message: Error executing action: Not connected. Not sure what else to try here. Any suggestions?

2023-10-14 01:44:18.0194|DEBUG|ColorControl.Program|Using data path: C:\Users\NiceBum\AppData\Roaming\Maassoft\ColorControl
2023-10-14 01:44:19.3529|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-10-14 01:44:19.3652|DEBUG|ColorControl.MainForm|No NVIDIA device detected: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)
2023-10-14 01:44:19.3652|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL_Main_Control_Create
2023-10-14 01:44:19.3652|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL2_Main_Control_Create
2023-10-14 01:44:19.3652|DEBUG|ColorControl.MainForm|No AMD device detected
2023-10-14 01:44:19.4717|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2023-10-14 01:44:20.9343|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:44:23.1183|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:25.7120|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:28.3025|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:28.8150|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:44:31.0038|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:33.7439|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:36.4002|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:36.9114|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:44:36.9114|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:44:51.6659|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:44:51.6691|ERROR|ColorControl.MainForm|System.InvalidOperationException: Not connected
   at ColorControl.Services.LG.LgDevice.CheckConnection() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 752
   at ColorControl.Services.LG.LgDevice.GenericPictureAction(Dictionary`2 parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 1013
   at ColorControl.Services.LG.LgDevice.ExecuteAction(InvokableAction action, String[] parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 713
   at ColorControl.MainForm.btnLgExpertColorGamut_Click(Object sender, EventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 3697
2023-10-14 01:44:53.7747|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:56.3444|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:58.9133|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:44:59.4181|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:45:03.2332|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:45:05.3444|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:45:07.9434|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:45:10.5204|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:45:11.0299|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:45:11.0299|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:45:12.2464|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:45:14.3262|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:45:16.9057|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:45:19.4844|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: 0x80072EFD
2023-10-14 01:45:19.9857|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:45:19.9857|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:45:56.2550|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:46:01.3222|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:46:06.8518|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:46:12.3816|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:46:12.8837|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:46:12.8837|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:46:12.8837|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:46:17.9001|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:46:23.4286|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:46:28.9994|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:46:29.5135|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:46:29.5135|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:48:15.3932|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:48:17.5079|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: 0x80072EFD
2023-10-14 01:48:20.0947|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: 0x80072EFD
2023-10-14 01:48:22.6704|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: 0x80072EFD
2023-10-14 01:48:23.1793|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:48:23.1793|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:48:34.5116|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.75:3001
2023-10-14 01:48:34.5116|ERROR|ColorControl.MainForm|System.InvalidOperationException: Not connected
   at ColorControl.Services.LG.LgDevice.CheckConnection() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 752
   at ColorControl.Services.LG.LgDevice.GenericPictureAction(Dictionary`2 parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 1013
   at ColorControl.Services.LG.LgDevice.ExecuteAction(InvokableAction action, String[] parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 713
   at ColorControl.MainForm.btnLgExpertColorGamut_Click(Object sender, EventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\MainForm.cs:line 3697
2023-10-14 01:48:39.5137|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:48:45.0403|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:48:50.5704|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.75:3001/: The operation has timed out.
2023-10-14 01:48:51.0862|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:49:36.0664|DEBUG|ColorControl.Program|Using data path: C:\Users\NiceBum\AppData\Roaming\Maassoft\ColorControl
2023-10-14 01:49:37.0731|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-10-14 01:49:37.0731|DEBUG|ColorControl.MainForm|No NVIDIA device detected: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)
2023-10-14 01:49:37.0843|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL_Main_Control_Create
2023-10-14 01:49:37.0843|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL2_Main_Control_Create
2023-10-14 01:49:37.0843|DEBUG|ColorControl.MainForm|No AMD device detected
2023-10-14 01:49:37.1684|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2023-10-14 01:49:47.1175|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:49:49.2629|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: 0x80072EFD
2023-10-14 01:50:03.7536|DEBUG|ColorControl.Program|Using data path: C:\Users\NiceBum\AppData\Roaming\Maassoft\ColorControl
2023-10-14 01:50:04.5122|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-10-14 01:50:04.5196|DEBUG|ColorControl.MainForm|No NVIDIA device detected: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)
2023-10-14 01:50:04.5196|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL_Main_Control_Create
2023-10-14 01:50:04.5196|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL2_Main_Control_Create
2023-10-14 01:50:04.5196|DEBUG|ColorControl.MainForm|No AMD device detected
2023-10-14 01:50:04.6069|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2023-10-14 01:50:15.0344|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:50:17.1851|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: 0x80072EFD
2023-10-14 01:50:51.8121|DEBUG|ColorControl.Program|Using data path: C:\Users\NiceBum\AppData\Roaming\Maassoft\ColorControl
2023-10-14 01:50:52.6110|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-10-14 01:50:52.6196|DEBUG|ColorControl.MainForm|No NVIDIA device detected: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)
2023-10-14 01:50:52.6196|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL_Main_Control_Create
2023-10-14 01:50:52.6196|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL2_Main_Control_Create
2023-10-14 01:50:52.6196|DEBUG|ColorControl.MainForm|No AMD device detected
2023-10-14 01:50:52.7096|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
2023-10-14 01:54:30.0342|DEBUG|ColorControl.Program|Using data path: C:\Users\NiceBum\AppData\Roaming\Maassoft\ColorControl
2023-10-14 01:54:33.3470|DEBUG|ColorControl.MainForm|Initializing NVIDIA...
2023-10-14 01:54:33.7512|DEBUG|ColorControl.MainForm|No NVIDIA device detected: Unable to load DLL 'nvapi64' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId) in .\Native\Helpers\DelegateFactory.cs:line 62
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]() in .\Native\Helpers\DelegateFactory.cs:line 40
   at NvAPIWrapper.Native.GeneralApi.Initialize() in .\Native\GeneralApi.cs:line 142
   at NvAPIWrapper.NVIDIA.Initialize() in .\NVIDIA.cs:line 62
   at ColorControl.Services.NVIDIA.NvService.Initialize() in .\Services\NVIDIA\NvService.cs:line 1118
   at ColorControl.Services.Common.ServiceBase`1..ctor(AppContextProvider appContextProvider) in .\Services\Common\ServiceBase.cs:line 41
   at ColorControl.Services.Common.GraphicsService`1..ctor(AppContextProvider appContextProvider) in .\Services\Common\GraphicsService.cs:line 18
   at ColorControl.Services.NVIDIA.NvService..ctor(AppContextProvider appContextProvider) in .\Services\NVIDIA\NvService.cs:line 149
   at ColorControl.MainForm.InitNvService() in .\MainForm.cs:line 260
2023-10-14 01:54:33.7512|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL_Main_Control_Create
2023-10-14 01:54:33.7512|ERROR|ATI.ADL.ADL|ADL-function not supported: ADL2_Main_Control_Create
2023-10-14 01:54:33.7512|DEBUG|ColorControl.MainForm|No AMD device detected
2023-10-14 01:54:37.7144|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: On
2023-10-14 01:54:37.7144|DEBUG|ColorControl.Services.LG.LgService|PowerModeChanged: MonitorOn
2023-10-14 01:54:38.9031|DEBUG|ColorControl.Shared.Forms.FormUtils|Detected NotificationState change from 0 to QUNS_ACCEPTS_NOTIFICATIONS
2023-10-14 01:54:48.5571|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:54:50.8029|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:54:53.3880|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:54:55.9932|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:54:56.5071|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:54:58.5743|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:01.1830|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:03.9156|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:04.4104|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:55:04.4104|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:55:04.4104|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:55:06.4785|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:09.0584|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:11.7932|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:12.2999|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:55:12.2999|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:55:19.0967|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:55:21.2586|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:23.8562|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:27.0596|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:27.5648|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:55:27.5648|DEBUG|ColorControl.Services.LG.LgDevice|Cannot refresh apps: no connection could be made
2023-10-14 01:55:27.5648|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.15:3001
2023-10-14 01:55:29.6614|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:32.2438|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:34.8241|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.15:3001/: The text associated with this error code could not be found.

2023-10-14 01:55:35.3146|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
2023-10-14 01:55:35.3146|ERROR|ColorControl.Services.LG.LgPanel|System.InvalidOperationException: Not connected
   at ColorControl.Services.LG.LgDevice.CheckConnectionAsync() in .\Services\LG\LgDevice.cs:line 773
   at ColorControl.Services.LG.LgDevice.GenericPictureAction(Dictionary`2 parameters) in .\Services\LG\LgDevice.cs:line 1098
   at ColorControl.Services.LG.LgDevice.ExecuteActionAsync(InvokableAction action, String[] parameters) in .\Services\LG\LgDevice.cs:line 744
   at ColorControl.Services.LG.LgPanel.btnLgExpertColorGamut_Click(Object sender, EventArgs e) in .\Services\LG\LgPanel.cs:line 959

**Comment by slurpentyne** [comment]
Fwiw this also popped up
![Screenshot_20231014-021100](https://github.com/Maassoft/ColorControl/assets/147909905/dc959306-49ae-42ec-bc45-0d47b28a6730)

**Comment by Maassoft** [comment]
The error code "0x80072EFD" indicates that it could not connect to the TV. Can you try pinging the TV from your PC?
`ping 192.168.1.75`
or
`ping 192.168.1.15`
(I see 2 different IPs in the log)
