### ISSUE TITLE
Exception in thread: Not connected

### ISSUE THREAD

**Issue by iGom** [Maassoft/ColorControl#318]
ColorControl stopped connecting to the TV even though it is detectable

Windows 11 Enterprise N
23H2
22635.3140

LG OLED42C34LA

```
---------------------------
Error
---------------------------
Exception in thread: Not connected

   at ColorControl.Services.LG.LgDevice.CheckConnectionAsync() in .\Services\LG\LgDevice.cs:line 776

   at ColorControl.Services.LG.LgDevice.SetSystemSettings(String name, String value) in .\Services\LG\LgDevice.cs:line 1052

   at ColorControl.Services.LG.LgGameBar.tbTrackBar_Scroll(Object sender, EventArgs e) in .\Services\LG\LgGameBar.cs:line 304

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   at ColorControl.Program.GlobalThreadExceptionHandler(Object sender, ThreadExceptionEventArgs e) in .\Program.cs:line 320

   at ColorControl.Program.MainAsync(String[] args) in .\Program.cs:line 159

   at ColorControl.Program.Main(String[] args) in .\Program.cs:line 51
---------------------------
OK   
---------------------------
```

**Comment by wornbb** [comment]
I have the same problem. Upvote
