### ISSUE TITLE
[Request] Possibility of auto switching presets or other automation

### ISSUE THREAD

**Issue by kuroderuta** [Maassoft/ColorControl#37]
Hi, would it be possible for a preset to switch upon launching an application? I would love to more tightly integrate and automate this application with others beside manually choosing it. For example it would be nice for a custom "Game Mode" preset to launch with a game and go back to an "Expert Mode" when closed. Perhaps detecting the process or an .exe

**Comment by Maassoft** [comment]
Thanks for the request. Currently I am already testing something like that. In a future versions you can configure a 'trigger' on a preset so that the preset is automatically executed when the required conditions are met. Besides the starting of a process, you can also choose a trigger that activates whenever a full screen application is starting. Such a trigger would cover all games at once (if you use full screen). At this moment the trigger will also activate when you start playing a full screen YouTube video and that might not be desired. So you'll need some exclusion settings as well. Also there will be other conditions like HDR/SDR because you probably want different presets for HDR. 
All in all this will take a while to implement and test it. I don't know exactly when it will be finished, but I'm working on it 😀

**Comment by Maassoft** [comment]
I've finally managed to create a stable enough release for this, version 4.0.0.0. Check it out!

**Comment by kuroderuta** [comment]
Hey! Unfortunately I got problems with the new version. The LG Controller tab is completely blank as well.
![ColorControl_Rm4ulK6oQ4](https://user-images.githubusercontent.com/73666590/129474378-71e7e471-b6c1-4104-94c2-5677a7fbfbed.png)

**Comment by Maassoft** [comment]
Hmm, is this error happening when you close the application? Seems that saving the config doesn't check if the devices are loaded (not null). Is the LG controller tab page the first tab page or do you have a Nvidia or AMD graphics card and the corresponding tab pages?

**Comment by kuroderuta** [comment]
It looks like that when I start it and open, the error only pops out when i clock on the Log tab.
![ColorControl_QSVfKPh8ak](https://user-images.githubusercontent.com/73666590/129493843-68c2a4fb-e482-419c-850a-ce2aba69b6b3.png)

**Comment by Maassoft** [comment]
I've created a new release, 4.1.0.0. Please check if your issue is resolved.

**Comment by kuroderuta** [comment]
New release threw me an error immediately but also when checking the Log tab as well as trying to right click on the tray icon. Then I restarted my PC just in case and the LG controller tab started showing up however none of the features were functional. Looks like it doesn't detect the GPU.

Right-clicking the tray error
![ColorControl_sWucIZpMIZ](https://user-images.githubusercontent.com/73666590/129573818-a9b94007-e519-4bb0-9484-5358146dfd13.png)


Log before restarting PC
```
2021-08-16 15:33:24.7999|DEBUG|ColorControl.MainForm|No NVIDIA device detected
2021-08-16 15:33:24.8279|DEBUG|ColorControl.MainForm|No AMD device detected
2021-08-16 15:33:25.0531|ERROR|ColorControl.MainForm|Error initializing LgService: Cannot convert object of type 'System.Int32' to type 'System.Collections.Generic.List`1[ColorControl.PresetTrigger]'
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AssignToPropertyOrField(Object propertyValue, Object o, String memberName, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertDictionaryToObject(IDictionary`2 dictionary, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AddItemToList(IList oldList, IList newList, Type elementType, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertListToObject(IList list, Type type, JavaScriptSerializer serializer, Boolean throwOnError, IList& convertedList)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at ColorControl.LgService.LoadPresets()
   at ColorControl.LgService..ctor(String dataPath, Boolean allowPowerOn)
   at ColorControl.MainForm.InitLgService()
```

Log after restarting
```
2021-08-16 15:38:07.7696|DEBUG|ColorControl.MainForm|No NVIDIA device detected
2021-08-16 15:38:07.8036|DEBUG|ColorControl.MainForm|No AMD device detected
2021-08-16 15:38:08.2711|ERROR|ColorControl.MainForm|Error initializing LgService: Object reference not set to an instance of an object.
   at ColorControl.MainForm.FillLgPresets()
   at ColorControl.MainForm.InitLgService()
2021-08-16 15:40:09.6442|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2021-08-16 15:40:12.0245|DEBUG|ColorControl.WOL|Found network: Ethernet (Realtek PCIe GbE Family Controller), type: Ethernet
2021-08-16 15:40:12.0245|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet (Realtek PCIe GbE Family Controller), local address: 192.168.50.3
2021-08-16 15:40:12.0245|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2021-08-16 15:40:26.1833|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2021-08-16 15:40:42.7013|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2021-08-16 15:40:59.2165|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2021-08-16 15:41:15.7359|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2021-08-16 15:41:29.5805|DEBUG|ColorControl.MainForm|No NVIDIA device detected
2021-08-16 15:41:29.6085|DEBUG|ColorControl.MainForm|No AMD device detected
2021-08-16 15:41:29.9558|ERROR|ColorControl.MainForm|Error initializing LgService: Object reference not set to an instance of an object.
   at ColorControl.MainForm.FillLgPresets()
   at ColorControl.MainForm.InitLgService()
```

**Comment by Maassoft** [comment]
That's strange. Are you maybe using Windows 11? It's possible there might be some compatibility issues. Do you have a Nvidia or AMD GPU?

**Comment by kuroderuta** [comment]
I should've mentioned, yes its on Windows 11, unfortunately no way to test on Win10 at the moment. I'm using Nvidia RTX 3080, latest Studio drivers.

**Comment by Maassoft** [comment]
I've tried Win11 in VirtualBox and ColorControl does start and LG controller tab is visible, but not functional due to not detecting any tv's. My Nvidia GPU isn't detected too, but that's no surprise because there's no GPU pass through.
ColorControl 3.3.0.0 did work correctly?

**Comment by kuroderuta** [comment]
Yeah no issues with 3.3.0.0

**Comment by Maassoft** [comment]
Maybe there's an issue loading the presets. Currently when loading the Nvidia presets throws an exception it will simply say you have no NVIDIA device, so that's not entirely correct behavior. What happens if you (temporarily) move the file "NvPresets.json" to another folder and start ColorControl 4.1.0.0 then? The file should be in this folder:

C:\Users\\_username_\AppData\Roaming\Maassoft\ColorControl

The same might be the case for the LgPresets.json. If moving this file solves the "Error initializing LgService", then there's a case in those presets that's not handled well in the new version. Maybe you can attach these files to your next comment, that makes it easier for me to debug this issue.

**Comment by kuroderuta** [comment]
The Nvidia Controller tab came back after I moved the NVPresets file, however nothing else changed, same errors all around. I had to move all files and now it all works again. I zipped the folder with the files.
[ColorControl.zip](https://github.com/Maassoft/ColorControl/files/7003029/ColorControl.zip)

**Comment by Maassoft** [comment]
I've found the problems and created a new release 4.2.0.0 which will solve the problems.
Your LgPresets-file was blank (null) though, so it will revert to the default presets automatically now.

**Comment by kuroderuta** [comment]
New version restored all the previous functionality so that's great! I tried some of the new automation features but they seem to be not working for me however. I followed the instructions as well as just manually inputting the process names without conditions but the presets just do not run. I suspect that actually might be some sort of incompatibility with Win11 but that's just my guess.

**Comment by kuroderuta** [comment]
Also the Picture Mode in the Expert options lacks the HDR Filmmaker mode? I tried the "hdrTechnicolor" thinking that might be filmmaker but that doesn't engage it.

**Comment by kuroderuta** [comment]
Trying to change Nvidia presets throws up this error:
`2021-08-18 12:56:33.4582|ERROR|ColorControl.NvService|SetColorData threw an exception: NVAPI_NOT_SUPPORTED`

**Comment by Maassoft** [comment]
Great that most problems are solved.
For the automation not working: can you test what happens after you activate the "Automatically power off on screensaver..." setting? It seems that the process monitor loop can bug out if this option is not activated.
HDR Filmmaker is a picture mode introduced with the CX series? Currently most of the functionality is based on the C9 series and therefore lacks some of the newer functions/modes. Maybe I will add it later.
What specific Nvidia setting are you changing? Not all combinations of color depth, dynamic range, color space, etc. are valid and will throw this error.

**Comment by kuroderuta** [comment]
It worked now after I activated the setting and restarted the program. Is there a way to go back to the previous/another preset after closing the fullscreen application?

And yeah I googled and it looks like SDR and HDR Filmmaker mode were added with LG CX, not terribly important as you can just create a manual preset for it but would be nice in the future.

Yes I think I figured it out it was just an user error on my part trying unsupported configurations.

**Comment by Maassoft** [comment]
To go back to another preset you need to create a "default" preset, which undoes all changes made by the preset for a specific program. I've described this in the release notes of 4.0.0.0: https://github.com/Maassoft/ColorControl/releases/tag/v4.0.0.0

**Comment by kuroderuta** [comment]
Awesome, looks like everything works as I originally wished it could, great work!
