### ISSUE TITLE
turnScreenOn being unresponsive

### ISSUE THREAD

**Issue by Blorkman** [Maassoft/ColorControl#381]
Hi, I'm having an issue.
I use turnScreenOff and turnScreenOn binded to shortcuts to, well turn on and off the screen of my lg C2, but recently turnScreenOn doesn't do anything if i dont spam the key.
I tried looking in the log but it seems to me that it just doesn't register the key press.
Still, sometimes (rarely) there's an error that may have something to do with it but I'm unable to decipher it :

LgTv.SendMessageException: Can't send message
LgTv.SendMessageException: Can't send message
 ---> System.Exception: 500 Application error
   at LgTv.LgTvApiCore.SendCommandAsync(String id, String message) in .\LgTv\LgTvConnection.cs:line 143
   --- End of inner exception stack trace ---
   at LgTv.LgTvApiCore.SendCommandAsync(String id, String message) in .\LgTv\LgTvConnection.cs:line 147
   at LgTv.LgTvApiCore.SendCommandAsync(RequestMessage message) in .\LgTv\LgTvConnection.cs:line 159
   at NLog.Logger.SwallowAsync[TResult](Func`1 asyncFunc, TResult fallback)

Any ideas ?

**Comment by Blorkman** [comment]
Ignore me im just retarded its the fucking key on my keyboard thats unresponsive lmao
