### ISSUE TITLE
LG Presets not working on 4.0.0.0

### ISSUE THREAD

**Issue by roughavoc** [Maassoft/ColorControl#41]
3.3.0.0 never had this issue

2021-08-15 14:59:36.5455|DEBUG|ColorControl.LgDevice|[[LG] webOS TV OLED55C9PLA] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2021-08-15 14:59:36.5455|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2021-08-15 14:59:36.5639|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: status: Unknown, exception: The best overloaded method match for 'int.Parse(string)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , Type , Object )
   at ColorControl.LgDevice.PictureSettingsChanged(Object payload)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)

LG Presets work for about 30 seconds before this error message, only how I've found to fix it is to redelete AppData folder and reconnect.

**Comment by roughavoc** [comment]
The steps I am calling

` pictureMode(expert2), backlight(33) `

**Comment by Maassoft** [comment]
I think this is caused by the picture settings subscription. The app is listening to changes of the backlight and contrast; whenever they change the tv sends a message to the app. ColorControl then parses the values of the message to numbers, but it seems the values are not integers in your case. That's strange, because I have a C9 as well. Anyway, I've already made some checks to this code so it doesn't crash again. A bugfix release will follow within a couple of days I hope.

**Comment by Maassoft** [comment]
I've created a new release, 4.1.0.0. Can you test if this issue is resolved?

**Comment by roughavoc** [comment]
The issue hasn't showed itself after testing for 15mins and the app is still working

However I am still getting these errors in the Log

2021-08-16 14:33:05.2785|DEBUG|ColorControl.LgDevice|PictureSettingsChanged: {"contrast":85,"backlight":"100"}
2021-08-16 14:33:05.2785|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: the callback threw an exception: The best overloaded method match for 'ColorControl.Utils.ParseInt(string, int)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , Type , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at ColorControl.LgDevice.PictureSettingsChanged(Object payload)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
2021-08-16 14:33:05.3715|DEBUG|ColorControl.LgDevice|PictureSettingsChanged: {"backlight":"100"}

The steps: Going from ISF Dark to ISF Bright and setting the backlight to 100 (I have 4 keybinds, ISF Dark 0, ISF Dark 33, ISF Bright 66, ISF Bright 100)

**Comment by Maassoft** [comment]
Thanks for the log. I think I see the problem. The contrast in the Json seems to be already a numeric value, while the backlight is a string (as I expect them both to be). I will add some extra checks in the next version.

**Comment by Maassoft** [comment]
With version 4.2.0.0 the errors in the log should not be popping up anymore. Have you had the chance to test it?

**Comment by roughavoc** [comment]
Log is empty now
Only thing that clutters the log is due to me having the presets.json set to read only to have hotkeys without modifiers from being overwritten :)

**Comment by Maassoft** [comment]
Ah, well I can remove the requirement of modifiers for the F13-F24 keys. Will that help you?

**Comment by roughavoc** [comment]
That would be sweet

**Comment by roughavoc** [comment]
As of 4.2.2.0

You can a shortcut with F13-24 but you cannot save it:

Invalid shortcut. The shortcut should have modifiers and a normal key.

**Comment by Maassoft** [comment]
I've fixed this with 4.2.3.0, I should test better myself 😁
