### ISSUE TITLE
ColorControl wakes up all configured TVs from screensaver when it turned off just one

### ISSUE THREAD

**Issue by farnoy** [Maassoft/ColorControl#96]
I have two TVs configured with "automatically power off/on with screensaver", but I only use one at any point in time.

ColorControl (sometimes?) powers on both of them when waking up from screensaver. It's usually fine with keeping track of the specific one it itself turned off.

<details>
<summary>Here's the relevant log dump</summary>

```
2022-04-23 23:20:51.0576|DEBUG|ColorControl.LgService|Screensaver started: scrnsave.scr, parent: winlogon
2022-04-23 23:20:51.0576|DEBUG|ColorControl.LgService|Screensaver check: test connection with LG salon TV...
2022-04-23 23:20:51.1584|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2022-04-23 23:20:51.1584|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-04-23 23:20:51.1747|DEBUG|ColorControl.LgDevice|[LG salon TV] PictureSettingsChanged: {"contrast":85,"backlight":"20","brightness":50,"color":50}
2022-04-23 23:20:51.1747|DEBUG|ColorControl.LgDevice|[LG salon TV] ForegroundAppChanged: {"appId":"com.webos.app.hdmi2","subscribed":true,"returnValue":true,"windowId":"","processId":""}
2022-04-23 23:20:51.1916|DEBUG|ColorControl.LgService|Screensaver check: test connection result: True
2022-04-23 23:20:51.1916|DEBUG|ColorControl.LgService|Screensaver check: powering off tv LG salon TV because of screensaver
2022-04-23 23:20:51.2825|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2022-04-23 23:20:51.2825|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-04-23 23:20:51.3019|DEBUG|ColorControl.LgDevice|[LG salon TV] PictureSettingsChanged: {"contrast":85,"backlight":"20","brightness":50,"color":50}
2022-04-23 23:20:51.3019|DEBUG|ColorControl.LgDevice|[LG salon TV] ForegroundAppChanged: {"appId":"com.webos.app.hdmi2","subscribed":true,"returnValue":true,"windowId":"","processId":""}
2022-04-23 23:20:51.4349|DEBUG|ColorControl.LgService|Screensaver check: powered off tv LG salon TV
2022-04-23 23:20:51.5008|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Power Off","onOff":"off","reason":"remoteKey"}
2022-04-23 23:20:51.5008|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: True
2022-04-23 23:20:51.9259|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Active Standby","onOff":"off","reason":"remoteKey"}
2022-04-23 23:20:51.9259|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: True
2022-04-23 23:20:52.0005|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"returnValue":true,"state":"Active","processing":"Request Suspend","onOff":"off","reason":"remoteKey"}
2022-04-23 23:20:52.0008|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: True
2022-04-23 23:21:40.9848|ERROR|LgTv.LgTvApiCore|Connection_MessageReceived: status: Timeout, exception: One or more errors occurred. (0x80072EE2)
Inner exception: 0x80072EE2
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\lgtv\LgTvConnection.cs:line 253
2022-04-23 23:21:52.7749|DEBUG|ColorControl.LgService|Screensaver stopped, waking
2022-04-23 23:21:52.7749|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 1 of 10...
2022-04-23 23:21:52.7973|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:21:52.7973|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:21:52.7973|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:21:52.7973|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:21:52.7973|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 1 of 10...
2022-04-23 23:21:52.7973|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:21:52.7973|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:21:52.7973|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:21:52.7973|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:21:53.8138|DEBUG|ColorControl.LgService|Process monitor: TV(s) where connected, but not any longer
2022-04-23 23:21:55.1304|DEBUG|ColorControl.LgService|Process monitor: test connection with LG desktop TV...
2022-04-23 23:21:58.8260|DEBUG|ColorControl.LgDevice|Connect succeeded: False
2022-04-23 23:21:58.8260|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 2 of 10...
2022-04-23 23:21:58.8349|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:21:58.8349|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:21:58.8349|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:21:58.8349|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:21:58.8569|DEBUG|ColorControl.LgDevice|Connect succeeded: False
2022-04-23 23:21:58.8569|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 2 of 10...
2022-04-23 23:21:58.8638|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:21:58.8638|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:21:58.8638|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:21:58.8638|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:22:04.3626|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2022-04-23 23:22:04.3626|DEBUG|ColorControl.LgService|Process monitor: test connection result: False
2022-04-23 23:22:04.3626|DEBUG|ColorControl.LgService|Process monitor: test connection with LG salon TV...
2022-04-23 23:22:04.9055|DEBUG|ColorControl.LgDevice|Connect succeeded: False
2022-04-23 23:22:04.9055|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 3 of 10...
2022-04-23 23:22:04.9135|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:22:04.9135|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:22:04.9135|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:22:04.9135|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:22:09.8808|DEBUG|ColorControl.LgDevice|Connect succeeded: False
2022-04-23 23:22:09.8808|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 3 of 10...
2022-04-23 23:22:09.8808|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:22:09.8808|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:22:09.8808|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:22:09.8808|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:22:10.4393|DEBUG|ColorControl.LgDevice|Cannot apply LG-preset: no connection could be made
2022-04-23 23:22:10.4393|DEBUG|ColorControl.LgService|Process monitor: test connection result: False
2022-04-23 23:22:11.4633|DEBUG|ColorControl.LgService|Process monitor: TV(s) where not connected, but connection has now been established
2022-04-23 23:22:12.9383|DEBUG|ColorControl.LgDevice|[LG salon TV] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2022-04-23 23:22:12.9383|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-04-23 23:22:13.0199|DEBUG|ColorControl.LgDevice|[LG salon TV] PictureSettingsChanged: {"contrast":85,"backlight":"20","brightness":50,"color":50}
2022-04-23 23:22:13.0590|DEBUG|ColorControl.LgDevice|[LG salon TV] ForegroundAppChanged: {"appId":"com.webos.app.hdmi2","subscribed":true,"returnValue":true,"windowId":"","processId":""}
2022-04-23 23:22:13.0590|DEBUG|ColorControl.LgDevice|Connect succeeded: True
2022-04-23 23:22:15.9356|DEBUG|ColorControl.LgDevice|Connect succeeded: False
2022-04-23 23:22:15.9356|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 4 of 10...
2022-04-23 23:22:15.9426|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:22:15.9426|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:22:15.9426|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:22:15.9426|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:22:21.9768|DEBUG|ColorControl.LgDevice|Connect succeeded: False
2022-04-23 23:22:21.9768|DEBUG|ColorControl.LgDevice|WakeAndConnectWithRetries: attempt 5 of 10...
2022-04-23 23:22:21.9850|DEBUG|ColorControl.WOL|Found network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), type: Ethernet
2022-04-23 23:22:21.9850|DEBUG|ColorControl.WOL|Broadcast WOL in network: Ethernet 2 (ASUS XG-C100C 10G PCI-E Network Adapter), local address: 192.168.100.2
2022-04-23 23:22:21.9850|DEBUG|ColorControl.WOL|Found network: Bluetooth Network Connection (Bluetooth Device (Personal Area Network)), type: Ethernet
2022-04-23 23:22:21.9850|DEBUG|ColorControl.LgDevice|WOL succeeded
2022-04-23 23:22:29.1811|DEBUG|ColorControl.LgDevice|[LG desktop TV] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
2022-04-23 23:22:29.1811|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
2022-04-23 23:22:29.2441|DEBUG|ColorControl.LgDevice|[LG desktop TV] PictureSettingsChanged: {"contrast":"85","backlight":"20","brightness":"50","color":"50"}
2022-04-23 23:22:29.2501|DEBUG|ColorControl.LgDevice|[LG desktop TV] ForegroundAppChanged: {"appId":"com.webos.app.hdmi4","subscribed":true,"returnValue":true,"windowId":"","processId":""}
2022-04-23 23:22:29.2501|DEBUG|ColorControl.LgDevice|Connect succeeded: True
```
</details>

`LG salon TV` is the one I was using, but it also turned `LG desktop TV` on after screensaver stopped.

**Comment by Maassoft** [comment]
Do you have the option "Power on even after manual power off" checked? If so, that might be causing this. 
If you stop working on a specific TV, do you manually power it off?

**Comment by farnoy** [comment]
I don't use that additional option and yeah, I manually power it off after I move to the other one (otherwise I risk an OS freeze if I switch displays while the previously-enabled one is off).

**Comment by farnoy** [comment]
I found it consistently does this. I even had one case where it turned on the display I was not using after a screensaver, I manually turned it off and it then turned it on again. Could be the WoL retries that it does, I'm not sure.

**Comment by farnoy** [comment]
Not connected to this issue, but could we get an option in the Expert menu to power on/off a specific device?

**Comment by Maassoft** [comment]
I think the app is probably not correctly registering that you manually powered off a specific TV.  Only when the "PoweredOffBy" equals to "Manually" it should skip that device when a power on is issued. In your log I see that the "PoweredOffBy" is always "Unknown", as seen in this line:
`2022-04-23 23:22:12.9383|DEBUG|ColorControl.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False`

I've just tested manually powering off my TV and it's not registering it as it should, so I'll try to fix that.

**Comment by Maassoft** [comment]
I've just released v5.7.1.0 which (hopefully) fixes this problem.

**Comment by farnoy** [comment]
I tested it briefly and it worked after I manually turned the other one off from the remote. I haven't yet tested if `PoweredOffBy` will be `Manual` after the 15min "No signal" screensaver is over and the TV powers itself off.

Thanks a lot!

**Comment by farnoy** [comment]
I think that fixed it. Everything has been working reliably since the update. Thanks again!
